name: Bug Report
description: Report an issue caused by NootedRed
labels: ["Bug"]
projects: ["ChefKissInc/2"]
assignees:
  - VisualEhrmanntraut
body:
  - type: markdown
    attributes:
      value: |
        This form isn't for you to ask for help with your configuration or request ETAs; it's to report behaviour that NootedRed should not be exhibiting under normal conditions!
  - type: dropdown
    id: macos_version
    attributes:
      label: macOS Version
      description: On which macOS version is the bug occurring, if not on all of them? Versions that do not appear in the dropdown are not supported.
      options:
        - Catalina
        - Big Sur
        - Monterey
        - Ventura
        - Sonoma
        - Sequoia
    validations:
      required: false
  - type: input
    id: cpu
    attributes:
      label: What is your CPU's model?
      description: Only Ryzen 1st gen to 5th gen, and 7030 series are supported.
      placeholder: ex. AMD Athlon Silver 3020e
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Please describe the behaviour in detail.
      placeholder: I clicked on X, then Y and Z happened.
    validations:
      required: true
  - type: textarea
    id: expected_behaviour
    attributes:
      label: What should've happened instead?
      placeholder: X should be doing Y.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: If applicable, attach the .gpuRestart, .panic, etc file related to this issue.
      description: |
        You can find those in `/Library/Logs/DiagnosticReports`.
        If attaching a panic, make sure it was created while you have `keepsyms=1` in your boot args (else the file is useless).
