name: Feature Request
description: Request a feature be added to NootedRed
labels: ["Enhancement"]
projects: ["ChefKissInc/2"]
assignees:
  - VisualEhrmanntraut
body:
  - type: markdown
    attributes:
      value: |
        This form isn't for you to ask for help with your configuration, report issues or request ETAs; it's to request features NootedRed is missing!
  - type: dropdown
    id: macos_version
    attributes:
      label: macOS Version
      description: On which macOS version is the feature missing, if not on all of them? Versions that do not appear in the dropdown are not supported.
      options:
        - Catalina
        - Big Sur
        - Monterey
        - Ventura
        - Sonoma
        - Sequoia
    validations:
      required: false
  - type: input
    id: cpu
    attributes:
      label: What is your CPU's model?
      placeholder: ex. AMD Athlon Silver 3020e
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Please describe the feature in detail.
      placeholder: I want NootedRed to be able to do Y.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: What alternatives have you tried, if any?
      placeholder: I used X to work around the lack of the feature.
    validations:
      required: true
